version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: proyectos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gaming_store
    ports:
      - "5432:5432"
    volumes:
      - proyectos_data:/var/lib/postgresql/data
    networks:
      - gaming_store_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gaming_store_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - gaming_store_network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  proyectos_data:
    name: proyectos_data
  redis_data:

networks:
  gaming_store_network:
    driver: bridge
