{
  "nixpacks": {
    "phases": {
      "install": {
        "cmds": ["npm install"]
      },
      "build": {
        "cmds": [
          "npx prisma generate",
          "npm run build"
        ]
      },
      "start": {
        "cmd": "npx prisma migrate deploy && npm run start"
      }
    }
  }
}
